export const CREATE_BOARD_REQUEST = "CREATE_BOARD_REQUEST";
export const CREATE_BOARD_SUCCESS = "CREATE_BOARD_SUCCESS";
export const CREATE_BOARD_FAILED = "CREATE_BOARD_FAILED";

export const GET_BOARDS_REQUEST = "GET_BOARDS_REQUEST";
export const GET_BOARDS_SUCCESS = "GET_BOARDS_SUCCESS";
export const GET_BOARDS_FAILED = "GET_BOARDS_FAILED";

export const GET_BOARD_NAME_SUCCESS = "GET_BOARD_NAME_SUCCESS";